### ISSUE TITLE
Welke frequentie voor het verversen van het Geoportaal?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#109]
@gerardnienhuis Met welke frequentie moet de inhoud van de database waarin wordt gezocht worden ververst? Is één keer per uur voldoende? Dus een beheerder kan binnen maximaal een uur nadat hij een metadata bestand heeft gewijzigd in betreffende map op de server van Overijssel dit bestand terugvinden in het Geoportaal.

**Comment by gerardnienhuis** [comment]
Ga ik uitzoeken

Verstuurd vanaf mijn iPhone

Op 14 apr. 2016 om 14:26 heeft Herman Assink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis Met welke frequentie moet de inhoud van de database waarin wordt gezocht worden ververst? Is één keer per uur voldoende? Dus een beheerder kan binnen maximaal een uur nadat hij een metadata bestand heeft gewijzigd in betreffende map op de server van Overijssel dit bestand terugvinden in het Geoportaal.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/109

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
1 x per half uur lijkt voldoende vaak

Verstuurd vanaf mijn iPhone

Op 14 apr. 2016 om 14:26 heeft Herman Assink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis Met welke frequentie moet de inhoud van de database waarin wordt gezocht worden ververst? Is één keer per uur voldoende? Dus een beheerder kan binnen maximaal een uur nadat hij een metadata bestand heeft gewijzigd in betreffende map op de server van Overijssel dit bestand terugvinden in het Geoportaal.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/109

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by gerardnienhuis** [comment]
steekproefsgewijs getest, geen tijden langer dan 30 minuten gevonden. blijkt te werken, issue kan gesloten
