### ISSUE TITLE
Slashes in thumbnail url zijn vaak verkeerd

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/geoportaal-test#136]
@gerardnienhuis: Bij de url's van de thumbnails in de metadata van datasets staan in de meeste gevallen de slashes de verkeerde kant op.

Voorbeeld: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\preview\twaarea.jpg

Chrome en IE corrigeren dit, maar in Firefox wordt dan geen thumbnail getoond.

Is dit iets wat aan jullie kant aangepast kan worden?

**Comment by gerardnienhuis** [comment]
Het meest verstandige is om ieder bestand (dus ook die thumbnails) te downloaden en via idgis beschikbaar te stellen. hierdoor ben je bij het nieuwe geoportaal niet meer afhankelijk van downtime van omgeving van Overijssel. En dan heb je het slash probleem ook niet meer.

**Comment by gerardnienhuis** [comment]
Het blijkt dat sommige componenten van Geosticker \ ipv / gebruiken.

Ik ga uitzoeken of hier iets aan te doen is, met de huidige software die we hebben.

Ik vrees dat aanpassen van Geosticker en de rest lastig is.

Is hier een alternatieve oplossing voor te bedenken?

Van: SandroNeumann [mailto:notifications@github.com]
Verzonden: vrijdag 22 april 2016 17:55
Aan: IDgis/geoportaal-test
CC: Nienhuis, G (Gerard); Mention
Onderwerp: [IDgis/geoportaal-test] Slashes in thumbnail url zijn vaak verkeerd (#136)

@gerardnienhuishttps://github.com/gerardnienhuis: Bij de url's van de thumbnails in de metadata van datasets staan in de meeste gevallen de slashes de verkeerde kant op.

Voorbeeld: http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\preview\twaarea.jpg

Chrome en IE corrigeren dit, maar in Firefox wordt dan geen thumbnail getoond.

Is dit iets wat aan jullie kant aangepast kan worden?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/136

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Onderzoeken of de Geoportaal programmatuur \ door / kan vervangen als er http voor staat

**Comment by gerardnienhuis** [comment]
Ik denk dat het nog niet goed werkt, zie ook #189 

ik tref nu 2 soorten slashes aan, waarvan die van de layerfile niet werkt, van de website wel, zie hieronder:

Aangemerkte Incident Managementwegen
http://acc-metadata.geodataoverijssel.nl/metadata/dataset/98d0107d-ad13-4176-86ac-6583f6e9c9d2.xml
Aanvullende informatie: layerfile:|http:\gisopenbaar.overijssel.nl\GeoPortal\MIS4GIS\lyr\im_netwerk_arc.lyr

Bestandsnaam: Buitendijks gebied of winterbed tbv Omgevingsvisie
http://acc-metadata.geodataoverijssel.nl/metadata/dataset/833b13cc-e644-4d27-bb45-f18429a08935.xml
Aanvullende informatie: Website| http://gisopenbaar.overijssel.nl/website/omgevingsvisie/omgevingsvisie.html?laag=omgevingsvisie&vis=axlID

**Comment by SandroNeumann** [comment]
Dit issue had alleen betrekking op de thumbnails. Bij het metadata element aanvullende informatie staat er ook een label voor de url, wat elk slash teken vervangen onverstandig maakt omdat je niet weet wat je buiten de url verandert.

**Comment by gerardnienhuis** [comment]
voorstel is om de thumbnails als bestand te harvesten en over te zetten naar omgeving van idgis: hierdoor ben je niet meer afhankelijk van eventuele downtime van omgeving van Overijssel. Je kan altijd nog geoportaal inclusief thumbnails blijven gebruiken. Nb.: staat ook als zodanig in FO (alle betreffende bestanden te hosten via idgis)

**Comment by gerardnienhuis** [comment]
dit probleem is opgelost: plaatjes en bijlagen worden door IDGis bewaard en beschikbaar gesteld via het Geoportaal: werkt nu goed. zie plaatje

 Issue kan gesloten.

![hosting_idgis_bijlagen_plaatjes](https://cloud.githubusercontent.com/assets/9005444/15738147/41533f4e-28aa-11e6-8245-9be47014e5d5.jpg)
