### ISSUE TITLE
Metadata van brondata versus metadata van gepubliceerde datasets

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoportaal-test#144]
@gerardnienhuis Wanneer verwacht je in het geoportaal de metadata van brondata te zien en wanneer de metadata van als service gepubliceerde dataset (die is gebaseerd op dezelfde brondata)?
Mijn voorstel: Als een brondataset gepubliceerd is in een service dan wordt wordt de metadata van de in een service gepubliceerde dataset getoond en niet meer de metadata v.d. brondata. Als de brondata niet is gepubliceerd dan wordt de metadata van de brondataset getoond. Akkoord?

**Comment by gerardnienhuis** [comment]
Akkoord als er alleen maar zinvolle data zoals url's bijkomen dan is dat prima

Als data verloren gaat dan liever niet

Verstuurd vanaf mijn iPhone

Op 25 apr. 2016 om 15:53 heeft Herman Assink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@gerardnienhuishttps://github.com/gerardnienhuis Wanneer verwacht je in het geoportaal de metadata van brondata te zien en wanneer de metadata van als service gepubliceerde dataset (die is gebaseerd op dezelfde brondata)?
Mijn voorstel: Als een brondataset gepubliceerd is in een service dan wordt wordt de metadata van de in een service gepubliceerde dataset getoond en niet meer de metadata v.d. brondata. Als de brondata niet is gepubliceerd dan wordt de metadata van de brondataset getoond. Akkoord?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/IDgis/geoportaal-test/issues/144

---

Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.

---

**Comment by HermanAssink** [comment]
Er gaat geen data verloren, er worden alleen de juiste url's van services ingevuld.

**Comment by gerardnienhuis** [comment]
lijkt me prima, in dat geval.

**Comment by SandroNeumann** [comment]
wordt al in 1.1. opgelost, dit issue kan gesloten

**Comment by HermanAssink** [comment]
Ten onrechte gesloten, komt mee in 1.1.0; moet worden getest.

**Comment by gerardnienhuis** [comment]
hangt samen met #280 ?

**Comment by gerardnienhuis** [comment]
#280 is getest en blijkt goed te werken. Wat moet er nog voor dit issue worden getest? Of is het zo dat als #280 is opgelost, ook dit issue gesloten kan worden?

**Comment by HermanAssink** [comment]
Dit issue stelt dat het Geoportaal ook metadata moet bevatten van brondata waarvan geen dataset in de Publicatieomgeving is aangemaakt. #280  gaat over de eis dat metadata alleen in het externe Geoportaal zichtbaar mag zijn als "Geoportaal extern" is ingevuld.

**Comment by gerardnienhuis** [comment]
Wij hebben getest of in het Geoportaal ook geodata en metadata te vinden is, die nog niet in services is gezet door de publicatieomgeving. Dat blijkt correct te werken, Issue kan dus gesloten.
